version: '3'

services:
  testnet:
    image: zkopru_testnet_geth:latest
    build:
      context: ../
      dockerfile: ./dockerfiles/Contract.geth.dockerfile
    ports:
      - '5000:5000'
    labels:
      kompose.service.expose: testnet
    command: sh /proj/run_geth.sh
  coordinator:
    image: zkopru_node:latest
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8888:8888'
      - '5354:5354'
    depends_on:
      - 'testnet'
    labels:
      kompose.service.expose: coordinator
    volumes:
      - '../dist/src:/generator/dist'
    command: >
      bash -c "nc -l -p 5354 &&
      node /generator/dist/coordinator.js"
  redis:
    image: redis
    ports:
      - '6379:6379'
    labels:
      kompose.service.expose: redis
  organizer:
    image: zkopru_node:latest
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - 'redis'
      - 'coordinator'
    volumes:
      - '../dist/src:/generator/dist'
    labels:
      kompose.service.expose: organizer
    environment:
      - ZKOPRU_BRANCH=${ZKOPRU_BRANCH}
      - ZKOPRU_COMMIT_HASH=${ZKOPRU_COMMIT_HASH}
      - TEST_BRANCH=${TEST_BRANCH}
      - TEST_COMMIT_HASH=${TEST_COMMIT_HASH}
    command: bash -c "node /generator/dist/organizer/index.js"
  wallet:
    image: zkopru_node:latest
    build:
      context: ../
      dockerfile: ./dockerfiles/Generator.dockerfile
    depends_on:
      - 'redis'
      - 'organizer'
    volumes:
      - '../dist/src:/generator/dist'
    labels:
      kompose.controller.type: deployment
    command: >
      bash -c "sleep 10 && node /generator/dist/wallet.js"
